# Generated by Django 4.2 on 2024-08-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_historicaldetallesolicitud_detallesolicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsolicitud',
            name='taza_interes',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='taza_interes',
        ),
        migrations.AddField(
            model_name='historicalsolicitud',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Tasa de interes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Tasa de interes'),
            preserve_default=False,
        ),
    ]
