# Generated by Django 4.2 on 2024-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_remove_historicalsolicitud_taza_interes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsolicitud',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
    ]
