# Generated by Django 4.2 on 2024-08-08 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institucion', '0001_initial'),
        ('creditos', '0004_alter_historicalsolicitud_monto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstaadoCredito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de eliminación')),
                ('descripcion', models.CharField(max_length=255, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Estado Credito',
                'verbose_name_plural': 'Estados credito',
                'db_table': 'Estados_Credito',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalSolicitud',
            new_name='HistoricalSolicitudCredito',
        ),
        migrations.RenameModel(
            old_name='Solicitud',
            new_name='SolicitudCredito',
        ),
        migrations.AlterField(
            model_name='historicalsolicitudcredito',
            name='lugar_solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='institucion.oficina'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='lugar_solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.oficina'),
        ),
        migrations.AlterModelTable(
            name='solicitudcredito',
            table='Solicitudes_Creditos',
        ),
        migrations.AlterModelTable(
            name='tipogarantia',
            table='Tipos_Garantia',
        ),
        migrations.AlterModelTable(
            name='tiposegmentacion',
            table='Tipos_Segmentacion',
        ),
        migrations.AlterModelTable(
            name='tiposolicitud',
            table='Tipos_Solicitud',
        ),
        migrations.CreateModel(
            name='HistoricalEstaadoCredito',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de modificación')),
                ('delete_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de eliminación')),
                ('descripcion', models.CharField(db_index=True, max_length=255, verbose_name='Descripcion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Estado Credito',
                'verbose_name_plural': 'historical Estados credito',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
